Always export final solution (#106)
pyroteus/goalie pull request #118
Opened 2024-03-03 22:48 UTC by ddundo

Closes #106 

@jwallwork23 here is the quick implementation of the solution I suggested. The number of exports stays the same as before, but now always includes the final solution (before it always included the first solution).

Also tagging @stephankramer and @acse-ej321 for awareness :)

2024-03-04 07:49 UTC, jwallwork23 requested changes
Thanks for this @ddundo.

Please could you use `reversed` instead of `np.flip`? Good to use Python build-ins rather than external packages, where possible.

Could you also do the same thing in `adjoint.py`?

2024-03-05 04:37 UTC, ddundo commented
This should be ready for a re-review now @jwallwork23 :) 

I also made the change I mention in the above comment. It looked like a bug to me

2024-03-05 08:14 UTC, jwallwork23 approved these changes
Thanks very much for this @ddundo! Your bugfix and test tweaks make sense to me.

Just two very minor requests. If you fix those then feel free to merge.

2024-03-05 08:14 UTC, jwallwork23 commented on goalie/adjoint.py
> +                ):
Similarly here.

2024-03-05 11:07 UTC, ddundo commented on goalie/mesh_seq.py
> +                ):
Nice! Done in eb187c0bb681061888e0b9409e2c8ac56856d633

2024-03-05 11:08 UTC, ddundo commented
Thanks Joe! I did as you suggested and will merge :)

2024-03-05 11:09 UTC, merged